import { NextResponse } from "next/server";
import { initDB, sql } from "@/lib/db";
import { hashPassword } from "@/lib/auth";

const demoUsers = [
  { email: "adebayo@propertycrm.com", password: "admin123", name: "Adebayo Okafor", role: "super_admin", team: "AI Operations" },
  { email: "chioma@propertycrm.com", password: "demo123", name: "Chioma Eze", role: "admin", team: "Property Sales" },
  { email: "folake@propertycrm.com", password: "demo123", name: "Folake Adeyemi", role: "manager", team: "Client Relations" },
  { email: "tunde@propertycrm.com", password: "demo123", name: "Tunde Bakare", role: "manager", team: "Legal & Compliance" },
  { email: "ngozi@propertycrm.com", password: "demo123", name: "Ngozi Nwosu", role: "agent", team: "Property Sales" },
  { email: "emeka@propertycrm.com", password: "demo123", name: "Emeka Obi", role: "agent", team: "Client Relations" },
  { email: "adaeze@propertycrm.com", password: "demo123", name: "Adaeze Igwe", role: "agent", team: "Property Sales" },
  { email: "chukwuemeka@propertycrm.com", password: "demo123", name: "Chukwuemeka Okoro", role: "agent", team: "Legal & Compliance" },
  { email: "bola@propertycrm.com", password: "demo123", name: "Bola Adekunle", role: "agent", team: "Client Relations" },
  { email: "kemi@propertycrm.com", password: "demo123", name: "Kemi Oladipo", role: "viewer", team: null },
];

const demoCustomers = [
  { email: "info@leadway-property.com", name: "Leadway Property Ltd", company: "Leadway Property", segment: "enterprise", plan: "enterprise", ltv: 48000000, csat: 4.7, total_tickets: 18 },
  { email: "james@perfectedhomes.com", name: "James Adegoke", company: "Perfected Homes", segment: "business", plan: "business", ltv: 23400000, csat: 4.5, total_tickets: 9 },
  { email: "blessing@royalcourt.com", name: "Blessing Okonkwo", company: "Royal Court Estates", segment: "pro", plan: "pro", ltv: 15600000, csat: 4.8, total_tickets: 6 },
  { email: "chidi@urban shelter.ng", name: "Chidi Emenike", company: "Urban Shelter", segment: "enterprise", plan: "enterprise", ltv: 52300000, csat: 4.6, total_tickets: 22 },
  { email: "funke@brickstone.com.ng", name: "Funke Akindele", company: "Brickstone Africa", segment: "pro", plan: "pro", ltv: 18900000, csat: 4.3, total_tickets: 11 },
  { email: "yemi@cosgrove.com", name: "Yemi Osinbajo Jr", company: "Cosgrove Investment", segment: "business", plan: "business", ltv: 27600000, csat: 4.9, total_tickets: 7 },
  { email: "nneka@sahadat.com", name: "Nneka Abdullahi", company: "Sahadat Homes", segment: "starter", plan: "starter", ltv: 4200000, csat: 4.2, total_tickets: 4 },
  { email: "kunle@mixta.com", name: "Kunle Adeyemi", company: "Mixta Africa", segment: "enterprise", plan: "enterprise", ltv: 61200000, csat: 4.8, total_tickets: 15 },
  { email: "zainab@pw.com", name: "Zainab Bello", company: "PropertyWorld Nigeria", segment: "business", plan: "business", ltv: 19800000, csat: 4.4, total_tickets: 13 },
  { email: "ade@renner.com", name: "Adeola Ogundimu", company: "Renner & Co Real Estate", segment: "starter", plan: "starter", ltv: 3600000, csat: 4.7, total_tickets: 2 },
];

const demoKnowledgeArticles = [
  { title: "How to List a New Property", content: "To list a property, navigate to Properties > Add New Listing and complete the property details form including address, price, bedrooms, bathrooms, and property type. Upload high-quality photos (minimum 800x600 resolution) and include a detailed description highlighting key features. Once submitted, the listing goes through a review process before appearing on the public portal.", collection: "Property Sales", status: "published", views: 2341, ai_used: 187, helpful: 93, tags: ["listings", "property", "how-to", "onboarding"] },
  { title: "Managing Tenant Inquiries via WhatsApp", content: "PropertyCRM routes all incoming WhatsApp messages from tenants directly into the unified inbox under the correct property thread. Set up auto-replies for common inquiries such as rent amounts, available units, and viewing schedules using the AI response templates. Each message is tagged with the property ID and tenant reference for seamless tracking across your team.", collection: "Tenant Management", status: "published", views: 1876, ai_used: 143, helpful: 91, tags: ["whatsapp", "tenants", "inquiries", "messaging"] },
  { title: "Understanding Land Documentation Requirements", content: "Nigerian property transactions require proper documentation beginning with the Certificate of Occupancy (C of O) issued by the state government as the primary proof of land ownership. Governor's Consent is mandatory whenever ownership changes hands and must be obtained from the state land registry. Additional documents include the Survey Plan, Deed of Assignment, and receipt of purchase which together form a complete title chain for any property.", collection: "Legal & Documentation", status: "published", views: 3456, ai_used: 267, helpful: 96, tags: ["documentation", "legal", "c-of-o", "governors-consent", "land"] },
  { title: "Setting Up Virtual Property Tours", content: "PropertyCRM integrates with Matterport and 360-degree camera providers to offer immersive virtual property tours. Enable the feature in Settings > Integrations > Virtual Tours and connect your Matterport or similar provider account. Upload 360 tour links to each property listing and they will be embedded automatically in the property detail page and shared with prospective buyers via WhatsApp or email.", collection: "Integrations", status: "published", views: 1543, ai_used: 112, helpful: 89, tags: ["virtual-tours", "360", "matterport", "integration"] },
  { title: "Configuring Property Matching AI", content: "The AI Property Matching engine analyzes buyer preferences including budget, location, property type, and must-have features to recommend suitable listings. Configure matching rules in Settings > AI > Property Matching by setting weightings for each criterion. Buyers receive personalized recommendations via their preferred channel and agents are notified of high-confidence matches for immediate follow-up.", collection: "Property Sales", status: "published", views: 2789, ai_used: 201, helpful: 94, tags: ["ai", "matching", "recommendations", "buyer-preferences"] },
  { title: "KYC Verification for Property Transactions", content: "All buyers must complete KYC verification before any property transaction can proceed. The verification process collects a valid government-issued ID (National ID, International Passport, or Driver's License), proof of address, and bank verification number (BVN). Verification is processed through our integrated KYC provider and results are stored securely in the customer profile for audit purposes.", collection: "Legal & Documentation", status: "published", views: 2134, ai_used: 167, helpful: 92, tags: ["kyc", "verification", "compliance", "buyer-verification"] },
  { title: "Understanding Service Charge Calculations", content: "Service charges are calculated based on the proportionate share of common area maintenance costs allocated to each unit in an estate. The formula divides total estate operating costs (security, landscaping, waste management, common area utilities) by the number of units, adjusted for unit size where applicable. Configure auto-calculation rules in Settings > Billing > Service Charges to generate invoices automatically on your chosen schedule.", collection: "Tenant Management", status: "published", views: 1654, ai_used: 123, helpful: 88, tags: ["service-charge", "billing", "estate-management", "calculations"] },
  { title: "Mortgage Pre-Qualification Workflow", content: "PropertyCRM connects buyers with partner lenders through an automated pre-qualification workflow. Buyers submit their financial information through a secure form and the system forwards the application to approved mortgage brokers. Pre-qualification decisions are returned within 48 hours and reflected in the buyer's profile, helping agents identify serious buyers and streamline the sales process.", collection: "Property Sales", status: "published", views: 1234, ai_used: 89, helpful: 87, tags: ["mortgage", "pre-qualification", "lenders", "financing"] },
  { title: "Escrow Payment Processing", content: "PropertyCRM integrates with trusted escrow service providers to handle secure payments for property deposits and transactions. When a buyer commits to a purchase, the system generates an escrow account and provides payment instructions. Funds are held securely until all conditions of the sale are met and both parties confirm completion, protecting both buyer and seller throughout the transaction.", collection: "Property Sales", status: "published", views: 1876, ai_used: 134, helpful: 90, tags: ["escrow", "payments", "security", "transaction"] },
  { title: "Setting Up Open House Scheduling", content: "Create open house events from the property listing page by selecting Schedule Open House and choosing your date, time, and viewing capacity. The system automatically notifies all matched buyers through their preferred channel and tracks RSVPs in real time. After the event, attendance data is logged and follow-up tasks are created for each attendee based on their engagement level.", collection: "Property Sales", status: "published", views: 987, ai_used: 76, helpful: 85, tags: ["open-house", "scheduling", "viewings", "events"] },
  { title: "Property Valuation Integration", content: "PropertyCRM connects with leading property valuation APIs including Nigerian Valuation Standards-compliant services to provide automated valuation models (AVMs). Enable the integration in Settings > Integrations > Valuation and configure which properties should receive auto-valuations. Valuation reports are generated on demand and can be attached to property listings or shared with clients directly.", collection: "Integrations", status: "published", views: 1543, ai_used: 112, helpful: 89, tags: ["valuation", "appraisal", "api", "property-value"] },
  { title: "Managing Multiple Property Listings", content: "Use the Bulk Upload feature under Properties > Bulk Import to manage hundreds of listings simultaneously via CSV or Excel file upload. The system validates all data fields including address, price, and property details before processing. For ongoing management, the Listing Dashboard provides filters for status, location, price range, and agent assignment to quickly find and update any listing.", collection: "Property Sales", status: "published", views: 2345, ai_used: 178, helpful: 91, tags: ["bulk-upload", "listings", "management", "csv-import"] },
  { title: "Title Search and Verification Process", content: "Before any property transaction, PropertyCRM initiates a title search through the state land registry to verify the legal owner and check for encumbrances. The search results include any existing mortgages, liens, or legal disputes attached to the property. Upload the verified title documents to the property record and the system tracks the verification status with automated reminders for renewal where applicable.", collection: "Legal & Documentation", status: "published", views: 1987, ai_used: 156, helpful: 93, tags: ["title-search", "verification", "land-registry", "due-diligence"] },
  { title: "Configuring WhatsApp for Property Inquiries", content: "Connect your WhatsApp Business account in Settings > Channels > WhatsApp by authenticating via the Meta Business API. Once connected, all incoming property inquiries are automatically routed to the correct agent based on the property they reference. Configure auto-responses for after-hours inquiries and set up quick-reply templates for common questions about pricing, availability, and viewing schedules.", collection: "Integrations", status: "published", views: 3421, ai_used: 234, helpful: 92, tags: ["whatsapp", "setup", "channel", "property-inquiries"] },
  { title: "Email Integration for Property Correspondence", content: "Set up email integration in Settings > Channels > Email Integration using your organization's IMAP and SMTP credentials. Configure rules to automatically categorize incoming emails by property reference, sender type (buyer, seller, tenant), and urgency. Outbound emails from the platform include property details and branded templates that maintain a professional appearance across all correspondence.", collection: "Integrations", status: "published", views: 2876, ai_used: 198, helpful: 89, tags: ["email", "imap", "smtp", "correspondence"] },
  { title: "Building a Property Knowledge Base", content: "Create a comprehensive knowledge base for buyers and tenants by navigating to Knowledge Base > Add Article. Organize articles into collections such as Buying Guide, Rental Process, Area Guides, and FAQs. Each article supports rich text formatting, images, and embedded videos. Enable AI search so that visitors can ask natural language questions and receive instant answers from your curated content.", collection: "Getting Started", status: "published", views: 1654, ai_used: 121, helpful: 88, tags: ["knowledge-base", "content", "buyers", "tenants"] },
  { title: "Understanding AI Property Recommendations", content: "The AI recommendation engine uses collaborative filtering and property attribute matching to suggest listings to prospective buyers. It analyzes viewing history, saved properties, inquiry patterns, and demographic data to build a buyer profile. Recommendations are scored by relevance and updated in real time as new listings are added or buyer preferences change.", collection: "Property Sales", status: "published", views: 2345, ai_used: 189, helpful: 91, tags: ["ai", "recommendations", "matching", "algorithms"] },
  { title: "Setting Up Agent Commission Tracking", content: "Configure commission structures in Settings > Billing > Commissions by defining percentages for different deal types including sales, rentals, and lease renewals. Each closed deal automatically calculates the commission owed to the responsible agent and logs it in their performance dashboard. Generate monthly commission reports in Analytics > Agent Performance to review earnings and payouts.", collection: "Getting Started", status: "published", views: 1234, ai_used: 89, helpful: 90, tags: ["commission", "agents", "tracking", "payments"] },
  { title: "Managing Lease Agreements Digitally", content: "PropertyCRM supports fully digital lease workflows from drafting to e-signature. Create lease templates in Settings > Templates > Leases with customizable fields for rent amount, duration, and special clauses. Send leases to tenants for digital signature via email or WhatsApp and track the signing status in real time. Completed leases are automatically stored in the tenant's profile and linked to the property record.", collection: "Tenant Management", status: "published", views: 1876, ai_used: 134, helpful: 90, tags: ["lease", "digital-signature", "agreements", "tenants"] },
  { title: "Property Inspection Checklist System", content: "Automate property inspections using customizable checklists accessible from the mobile app. Create inspection templates for different property types including move-in, move-out, and routine inspections. Agents complete inspections on-site using their mobile devices, capturing photos and notes for each checklist item. Inspection reports are automatically generated and shared with relevant parties.", collection: "Tenant Management", status: "published", views: 1543, ai_used: 112, helpful: 89, tags: ["inspection", "checklist", "mobile", "property-management"] },
  { title: "Handling Deposit and Payment Collections", content: "Configure payment collection workflows in Settings > Billing > Payment Collections to automate deposit requests, rent invoices, and service charge reminders. The system sends payment reminders via the tenant's preferred channel and tracks payment status in real time. Overdue payments trigger escalation notifications to both the tenant and the assigned property manager for timely follow-up.", collection: "Tenant Management", status: "published", views: 2109, ai_used: 167, helpful: 91, tags: ["deposits", "payments", "collections", "billing"] },
  { title: "Multi-Agent Collaboration Tools", content: "PropertyCRM enables seamless collaboration between agents through shared property workspaces. Assign multiple agents to a single listing, share notes and client feedback in the internal discussion thread, and track who handled each client interaction. The activity log provides a complete history of all agent actions on a property for transparency and accountability.", collection: "Getting Started", status: "published", views: 987, ai_used: 78, helpful: 85, tags: ["collaboration", "teamwork", "agents", "shared-workspace"] },
  { title: "Real-Time Property Availability Updates", content: "Property inventory syncs in real time across all connected channels including the web portal, mobile app, and third-party listing sites. When a property status changes to sold, rented, or off-market, the update propagates instantly to prevent duplicate inquiries. Enable webhook notifications in Settings > Integrations > Webhooks to push availability changes to external systems and partner platforms.", collection: "Property Sales", status: "published", views: 1654, ai_used: 123, helpful: 88, tags: ["availability", "inventory", "real-time", "sync"] },
  { title: "Client Communication Preferences", content: "Each client profile includes a Communication Preferences section where their preferred channels, contact times, and language are recorded. The system respects these preferences when sending property updates, viewing reminders, and follow-up messages. Agents can view and update preferences from the client detail page and the AI routing agent uses this data to determine the best channel for each interaction.", collection: "Client Relations", status: "published", views: 1234, ai_used: 89, helpful: 87, tags: ["communication", "preferences", "client-management", "channels"] },
  { title: "Setting Up Property Alert Notifications", content: "Buyers can subscribe to property alerts by specifying their criteria including location, price range, property type, and number of bedrooms. The system monitors new listings in real time and sends instant notifications via WhatsApp, email, or SMS when a matching property is listed. Alert frequency can be configured as instant, daily digest, or weekly roundup based on buyer preference.", collection: "Property Sales", status: "published", views: 1432, ai_used: 109, helpful: 87, tags: ["alerts", "notifications", "buyer-preferences", "matching"] },
  { title: "Understanding Property Tax Calculations", content: "PropertyCRM automatically calculates applicable taxes including Land Use Charge, Stamp Duty, and Capital Gains Tax based on the transaction type and property location. Tax rates are configured in Settings > Billing > Tax Rules and can be customized by state. The system generates tax estimates during the deal negotiation phase and produces compliance reports for audit purposes.", collection: "Legal & Documentation", status: "published", views: 1876, ai_used: 134, helpful: 90, tags: ["tax", "property-tax", "compliance", "calculations"] },
  { title: "Configuring SLA for Property Inquiries", content: "Set up SLA rules specific to property inquiries in Settings > SLA Rules. Define response time targets for different inquiry types: viewing requests (2 hours), pricing questions (4 hours), and general inquiries (8 hours). Configure escalation triggers when SLAs are at risk and automatic reassignment rules when an agent does not respond within the specified timeframe. SLA compliance is tracked on the dashboard in real time.", collection: "Getting Started", status: "published", views: 1123, ai_used: 87, helpful: 86, tags: ["sla", "response-time", "inquiries", "configuration"] },
  { title: "Data Export and Privacy (NDPR)", content: "PropertyCRM complies with the Nigeria Data Protection Regulation (NDPR) and allows full data export from Settings > Data > Export. Export formats include CSV, JSON, and PDF for tickets, customer records, and property data. Data retention policies are configurable with a default of 90 days for messages and 2 years for transaction records. Submit data deletion requests through the privacy portal at privacy@propertycrm.com.", collection: "Technical Docs", status: "published", views: 1234, ai_used: 89, helpful: 90, tags: ["ndpr", "privacy", "data-export", "compliance", "regulation"] },
  { title: "Troubleshooting API Errors", content: "When encountering API errors, first verify your API key is valid and active in Settings > API > Keys. Common errors include 401 (authentication failure), 429 (rate limit exceeded at 1000 requests per minute), and 500 (server error). Check the API status page at status.propertycrm.com for ongoing incidents. For persistent issues, enable debug logging in Settings > API > Logging and share the request ID with support.", collection: "Troubleshooting", status: "published", views: 2876, ai_used: 198, helpful: 86, tags: ["api", "errors", "troubleshooting", "debugging"] },
  { title: "Mobile App for Property Agents", content: "The PropertyCRM mobile app is available on iOS and Android and provides agents with on-the-go access to their listings, client contacts, and scheduled viewings. Key features include on-site inspection checklists, photo capture with auto-tagging to property records, push notifications for new inquiries, and offline mode for viewing property details in areas with poor connectivity. Download from the App Store or Google Play and log in with your PropertyCRM credentials.", collection: "Getting Started", status: "published", views: 3456, ai_used: 245, helpful: 94, tags: ["mobile", "app", "agents", "ios", "android"] },
];

const demoTickets = [
  { subject: "Property viewing request for Lekki Phase 1 duplex", message: "I would like to schedule a physical inspection of the 4-bedroom duplex listed at Lekki Phase 1. Are there available slots this weekend?", status: "open", priority: "high", channel: "whatsapp", sentiment: "neutral", sentiment_score: 0.1, ai_confidence: 95, tags: ["viewing", "scheduling", "lekki"] },
  { subject: "Need C of O verification for Ikoyi property", message: "We are processing a sale for a property in Ikoyi and need to verify the Certificate of Occupancy. The title reference number is IKY/2019/LND/4521. Please confirm authenticity.", status: "escalated", priority: "urgent", channel: "email", sentiment: "neutral", sentiment_score: 0.0, ai_confidence: 82, tags: ["c-of-o", "verification", "ikoyi", "legal"] },
  { subject: "Tenant complaining about water supply in Banana Island", message: "Our tenant in Banana Island Estate has reported intermittent water supply for the past two weeks. The estate management says it is a pump issue but we need an urgent resolution.", status: "pending", priority: "high", channel: "whatsapp", sentiment: "frustrated", sentiment_score: -0.4, ai_confidence: 88, tags: ["tenant-issue", "maintenance", "banana-island"] },
  { subject: "Payment confirmation for property deposit at Chevron", message: "We have completed the transfer of the 10 million naira deposit for the property at Chevron Estate. Please confirm receipt and update the transaction status.", status: "open", priority: "medium", channel: "email", sentiment: "positive", sentiment_score: 0.3, ai_confidence: 91, tags: ["payment", "deposit", "chevron", "confirmation"] },
  { subject: "How do I schedule a virtual tour?", message: "I am interested in a property on the platform but I am currently outside Lagos. Is there a way to schedule a virtual tour or get a video walkthrough?", status: "open", priority: "low", channel: "web", sentiment: "neutral", sentiment_score: 0.2, ai_confidence: 97, tags: ["virtual-tour", "how-to", "feature-question"] },
  { subject: "Agent commission not reflected after closing", message: "I closed a deal on the Victoria Island apartment last week but the commission has not appeared in my dashboard. The deal reference is PCR-DEAL-2024-0892.", status: "escalated", priority: "high", channel: "email", sentiment: "angry", sentiment_score: -0.6, ai_confidence: 85, tags: ["commission", "payment", "agent", "vi"] },
  { subject: "Request for property valuation report", message: "We need a professional valuation report for a 5-bedroom detached house in Maitama, Abuja. The client requires it for mortgage application purposes.", status: "pending", priority: "medium", channel: "email", sentiment: "neutral", sentiment_score: 0.0, ai_confidence: 89, tags: ["valuation", "report", "abuja", "mortgage"] },
  { subject: "Service charge dispute from estate residents", message: "Residents of Garden Estate in Lekki are disputing the Q4 service charge increase. They claim the 35% increase was not communicated. We need to provide a breakdown of costs.", status: "open", priority: "medium", channel: "web", sentiment: "negative", sentiment_score: -0.3, ai_confidence: 87, tags: ["service-charge", "dispute", "estate", "billing"] },
  { subject: "Documentation for property transfer to new owner", message: "We have completed the sale of the Ikoyi commercial property and need assistance preparing the Deed of Assignment, Governor's Consent application, and all transfer documentation.", status: "open", priority: "high", channel: "email", sentiment: "neutral", sentiment_score: 0.1, ai_confidence: 90, tags: ["transfer", "documentation", "deed", "governors-consent"] },
  { subject: "Bulk listing upload not working", message: "I tried uploading 45 property listings via the CSV template but the system keeps showing a validation error on row 12. The error message says 'Invalid property type'. I have checked the data and it looks correct.", status: "open", priority: "medium", channel: "web", sentiment: "frustrated", sentiment_score: -0.3, ai_confidence: 84, tags: ["bulk-upload", "csv", "error", "technical"] },
];

export async function POST() {
  try {
    await initDB();

    for (const user of demoUsers) {
      const hash = await hashPassword(user.password);
      await sql`
        INSERT INTO users (email, password_hash, name, role, team)
        VALUES (${user.email}, ${hash}, ${user.name}, ${user.role}, ${user.team})
        ON CONFLICT (email) DO NOTHING
      `;
    }

    const customerIds: string[] = [];
    for (const c of demoCustomers) {
      const result = await sql`
        INSERT INTO customers (email, name, company, segment, plan, ltv, csat, total_tickets)
        VALUES (${c.email}, ${c.name}, ${c.company}, ${c.segment}, ${c.plan}, ${c.ltv}, ${c.csat}, ${c.total_tickets})
        ON CONFLICT (email) DO UPDATE SET name = ${c.name}
        RETURNING id
      `;
      customerIds.push(result[0].id);
    }

    const users = await sql`SELECT id, email FROM users`;
    const userIdMap: Record<string, string> = {};
    for (const u of users) userIdMap[u.email] = u.id;

    for (let i = 0; i < demoTickets.length; i++) {
      const t = demoTickets[i];
      const customerId = customerIds[i % customerIds.length];
      const assigneeId = userIdMap["ngozi@propertycrm.com"];
      const ticketNumber = `PCR-${1234 - i}`;
      const slaDue = new Date(Date.now() + (t.priority === "urgent" ? 3600000 : t.priority === "high" ? 7200000 : 14400000));

      await sql`
        INSERT INTO tickets (ticket_number, subject, message, status, priority, channel, customer_id, assignee_id, sentiment, sentiment_score, ai_confidence, sla_status, sla_due, tags)
        VALUES (${ticketNumber}, ${t.subject}, ${t.message}, ${t.status}, ${t.priority}, ${t.channel}, ${customerId}, ${assigneeId}, ${t.sentiment}, ${t.sentiment_score}, ${t.ai_confidence}, 'ok', ${slaDue.toISOString()}, ${t.tags})
        ON CONFLICT (ticket_number) DO NOTHING
      `;
    }

    const adminUserId = userIdMap["adebayo@propertycrm.com"];
    await sql`DELETE FROM knowledge_articles`;
    for (const article of demoKnowledgeArticles) {
      await sql`
        INSERT INTO knowledge_articles (title, content, collection, status, views, ai_used, helpful, tags, created_by)
        VALUES (${article.title}, ${article.content}, ${article.collection}, ${article.status}, ${article.views}, ${article.ai_used}, ${article.helpful}, ${article.tags}, ${adminUserId})
      `;
    }

    return NextResponse.json({
      message: "Database seeded successfully",
      logins: {
        admin: "adebayo@propertycrm.com / admin123",
        manager: "folake@propertycrm.com / demo123",
        agent: "ngozi@propertycrm.com / demo123",
        viewer: "kemi@propertycrm.com / demo123",
      },
    });
  } catch (error) {
    console.error("Seed error:", error);
    return NextResponse.json({ error: "Failed to seed database" }, { status: 500 });
  }
}
